Add instructions for poetry shell and pyenv
vintasoftware/django-ai-assistant pull request #154
Opened 2024-07-12 18:02 UTC by rodrigovieira-vinta

While I was setting up the project locally, I had an issue with the version of Python required. This PR adds some instructions on how to use `pyenv` to handle this issue.

Additionally, it adds instructions on how to use `poetry shell` to instantiate the virtual env specified on `pyproject.toml`

2024-07-12 18:24 UTC, fjsj commented on CONTRIBUTING.md
> +If you need to install the version of Python recommented for the project, you can use [Pyenv](https://github.com/pyenv/pyenv).
Typo: recommented -> recommended

2024-07-12 18:24 UTC, fjsj requested changes
Overall LGTM, but there's a small typo

2024-07-12 18:45 UTC, fjsj approved these changes

2024-08-06 20:34 UTC, filipeximenes commented
Ugh, I didn't see this PR and opened this [other one](https://github.com/vintasoftware/django-ai-assistant/pull/158) which adds the instruction to activate `poetry shell`, sorry.

2024-08-06 21:03 UTC, fjsj commented
Can you make sure we also drop the mention to pipenv? @filipeximenes

2024-08-06 21:06 UTC, filipeximenes commented
@fjsj will do. @rodbv I can't commit on your repository so I'll pull from your branch and open a new PR with these changes ok?

2024-08-07 16:01 UTC, rodrigovieira-vinta commented
> @fjsj will do. @rodbv I can't commit on your repository so I'll pull from your branch and open a new PR with these changes ok?

Sure!

2024-08-07 18:04 UTC, merged