add message inline to thread admin
vintasoftware/django-ai-assistant pull request #155
Opened 2024-07-14 12:39 UTC by ilikerobots

2024-07-18 19:21 UTC, amandasavluchinske commented
Hey @ilikerobots , thanks for your contribution!

Just wanted to give you a heads up that @fjsj is on PTO right now and will be coming back on Aug 1st. He'll have a look at your PR once he's back.

2024-08-06 20:29 UTC, filipeximenes requested changes

2024-08-06 20:29 UTC, filipeximenes commented on django_ai_assistant/admin.py
> +    inlines: ClassVar[InlineModelAdmin] = [MessageInline]
I believe the correct type annotation here is `List[Type[InlineModelAdmin]]`

2024-08-06 20:29 UTC, filipeximenes commented on django_ai_assistant/admin.py
> +        if display_text:
Please correct if I'm wrong, but I believe it's not possible for this `if` statement to resolve ever be falsy, I think we can remove it and return directly

2024-08-06 20:29 UTC, filipeximenes commented on django_ai_assistant/admin.py
> +    list_display = ("id", "thread", "created_at")
Good catch!

2024-08-13 14:34 UTC, closed without merging

2024-08-13 14:36 UTC, filipeximenes commented
Thanks for your contributions @ilikerobots! I've taken the liberty to address the issues and merge your changes (#159).